<a href="https://colab.research.google.com/github/sdsyjh/cnn-captcha-pytorch/blob/main/%E4%BB%8B%E7%BB%8Dcolab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = 10
y = 20
z = x + y

In [ ]:
print(f"z={z}")

z=30


In [5]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [7]:
import numpy as np
np1 = np.random.rand(3, 4)
print(np1)

[[0.97858538 0.36866416 0.06407956 0.01505028]
 [0.68416288 0.96069399 0.95616604 0.14573879]
 [0.06142376 0.07593274 0.3698581  0.48071006]]


In [10]:
import torch
tensor_2d = torch.randn(3, 4)
print(tensor_2d)

tensor([[ 0.1505, -1.3094, -0.3380,  2.0312],
        [-0.9060, -0.3610,  1.5211, -0.5037],
        [ 0.2603, -0.3415, -0.2595,  0.4819]])


In [13]:
my_tensor = torch.tensor(np1)
print(my_tensor)

tensor([[0.9786, 0.3687, 0.0641, 0.0151],
        [0.6842, 0.9607, 0.9562, 0.1457],
        [0.0614, 0.0759, 0.3699, 0.4807]], dtype=torch.float64)
